GET http://localhost:3003/api/blogs/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IlRlc3QiLCJpZCI6IjY2NTg1NzY2NDViYjNlY2ZiZDUyZThmMiIsImlhdCI6MTcxODE5MjI4M30.y97NZSbQ-VM1DChRb0hy01czaB1v9OdyQhAU-u0FJwU